// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDictionary.Infrastructure.Persistence;

#nullable disable

namespace MyDictionary.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208162723_Alter_Entity_WordForm")]
    partial class Alter_Entity_WordForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDictionary.Domain.Modules.DictionaryItemExamples.DictionaryItemExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DictionaryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Translation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryItemId");

                    b.ToTable("DictionaryItemExamples");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.DictionaryItems.DictionaryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DictionaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Term");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Term"), false);

                    b.HasIndex("DictionaryId", "Deleted");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("DictionaryId", "Deleted"), false);

                    b.ToTable("DictionaryItems");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.UserDictionaries.UserDictionary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDictionaries");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.WordForms.WordForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DictionaryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Infinitive")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PastParticiple")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PastSimple")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryItemId")
                        .IsUnique();

                    b.ToTable("WordForms");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.DictionaryItemExamples.DictionaryItemExample", b =>
                {
                    b.HasOne("MyDictionary.Domain.Modules.DictionaryItems.DictionaryItem", "DictionaryItem")
                        .WithMany("Examples")
                        .HasForeignKey("DictionaryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DictionaryItem");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.DictionaryItems.DictionaryItem", b =>
                {
                    b.HasOne("MyDictionary.Domain.Modules.UserDictionaries.UserDictionary", "Dictionary")
                        .WithMany("Items")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.UserDictionaries.UserDictionary", b =>
                {
                    b.HasOne("MyDictionary.Domain.Modules.Users.User", "User")
                        .WithMany("Dictionaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.WordForms.WordForm", b =>
                {
                    b.HasOne("MyDictionary.Domain.Modules.DictionaryItems.DictionaryItem", "DictionaryItem")
                        .WithOne("WordForm")
                        .HasForeignKey("MyDictionary.Domain.Modules.WordForms.WordForm", "DictionaryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DictionaryItem");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.DictionaryItems.DictionaryItem", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("WordForm");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.UserDictionaries.UserDictionary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDictionary.Domain.Modules.Users.User", b =>
                {
                    b.Navigation("Dictionaries");
                });
#pragma warning restore 612, 618
        }
    }
}
